- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
  - name: Disable VMWare VMs
    vmware_guest_powerstate:
      hostname: '{{ vcenter_host }}'
      username: "{{ vcenter_username | default('Administrator@vsphere.local')}}"
      password: '{{ vcenter_password }}'
      validate_certs: no
      name: "{{ item.strip() }}"
      state: powered-off
      force: yes
    with_items: "{{ vcenter_vm_names.split(',') | list }}"
  - name: Sleep for some time before enabling of VMs
    pause:
      seconds: "{{ downtime_in_seconds | default(30) }}"
  - name: Enable VMWare VMs back
    vmware_guest_powerstate:
      hostname: '{{ vcenter_host }}'
      username: "{{ vcenter_username | default('Administrator@vsphere.local')}}"
      password: '{{ vcenter_password }}'
      validate_certs: no
      name: "{{ item.strip() }}"
      state: powered-on
      force: yes
    with_items: "{{ vcenter_vm_names.split(',') | list }}"
